on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the application
        run: pnpm build

      - name: Run tests
        run: pnpm test
